server:
  port: 9998
spring:
  cloud:
    gateway:
      routes:
        - predicates:
            - Path=/gateway/** # 路径匹配
          filters:
            - StripPrefix=1 # 跳过前缀
          uri: http://localhost:9999/say # spring-cloud-gateway-service 访问地址
